### ISSUE TITLE
Settings not saving.

### ISSUE THREAD

**Issue by jackiellowery** [wnmp/wnmp#58] opened 2015-09-14 02:40 UTC
I run Windows 10 and WNMP 2.1.9.0.  When i check the "minimize to tray" option, besides not having any context menu options for the tray icon(another issue already reported), the option isn't saved.

Edit: Actually, I've noticed none of the options are saving.

**Comment by x64architecture** [comment] 2015-09-14 08:09
duplicate of #55

**Closed** 2015-09-14 08:09 UTC
Labels: duplicate
