### ISSUE TITLE
Download link broken. Website unavailable.

### ISSUE THREAD

**Issue by suchislife801** [wnmp/wnmp#105] opened 2018-10-17 13:05 UTC
Download link broken. Website unavailable. Can you please host latest versions here?

**Comment by mittus** [comment] 2018-10-17 14:09
You can download wnmp here: https://github.com/wnmp/wnmp/releases

**Comment by x64architecture** [comment] 2018-11-12 08:21
duplicate of #103.

**Closed by x64architecture** 2018-11-12 08:21 UTC
Labels: duplicate
