### ISSUE TITLE
Can't switch to PHP 7.x

### ISSUE THREAD

**Issue by Destroy666x** [wnmp/wnmp#69] opened 2015-12-19 16:38 UTC
1. Download latest 7.x http://windows.php.net/download#php-7.0 x86 or x64
2. Create folder called `7.0.1` in phpbins, copy files, rename php development ini
3. In Wnmp control panel options switch PHP version to 7.0.1

After starting PHP, it will stop after 5-10 seconds. Custom 5.x versions are working fine.

Windows 7 SP1.

**Comment by x64architecture** [comment] 2015-12-24 08:16
Do you have the Visual Studio 2015 x86 or x64 redistributes installed?

**Comment by Destroy666x** [comment] 2015-12-24 15:31
Yes

**Comment by x64architecture** [comment] 2015-12-28 21:50
Maybe its another issue? I can't reproduce.

**Comment by Destroy666x** [comment] 2015-12-28 22:33
What kind of an issue could it be?

I also tried WN-NMP and no problems with PHP 7 there.

**Comment by c2q1989** [comment] 2016-01-25 04:06
You might try to move the default files in /php directory to /phpbins. Remember, create a new folder as you said. Then, put the PHP7 binaries in /php directory, so this version will become the default.
In Windows 10 x64, I found this did works! Hoping your problem could be solved

**Comment by x64architecture** [comment] 2016-01-31 00:38
Can reproduce looking into it.

**Comment by x64architecture** [comment] 2016-01-31 01:12
comment out the php_opcache.dlll in php.ini the problem is that nginx and php opcache conflict.

**Comment by x64architecture** [comment] 2016-01-31 01:36
https://trac.nginx.org/nginx/ticket/888

**Comment by Destroy666x** [comment] 2016-01-31 01:50
I never had it enabled

**Comment by x64architecture** [comment] 2016-01-31 02:06
There's another issue with php opcache. I figured out the solution to your problem, Wnmp doesn't use the right php.ini when using custom php versions. It will be fixed in the next release.

**Closed** 2016-01-31 02:18 UTC

**Comment by vgaka** [comment] 2020-05-03 09:12
try lookup system monitor make sure your "Wnmp -> Options -> PHP port " is available before start php in Wnmp control panel. I'm success after change new port number.
